Add files via upload
amir-fatyhow/java-filmorate pull request #10
Opened 2022-07-29 06:40 UTC by amir-fatyhow

2022-07-29 13:11 UTC, Frilock requested changes
Добрый день, написал ряд комментариев по работе, жду новую версию.

2022-07-29 13:11 UTC, Frilock commented on target/classes/application.properties
> +
Добавьте папку targer в gitignore, это же скомпилированные классы

2022-07-29 13:11 UTC, Frilock commented on src/main/resources/schema.sql
> +DROP TABLE IF EXISTS friends;
По заданию вам в readme должна быть ссылка на файл диаграммы.

2022-07-29 13:11 UTC, Frilock commented on src/main/resources/data.sql
> +INSERT INTO genres(genre_id, genre)
А для чего этот скрипт с заполнением? Если для тестов то суньте его в ресурсы тестов

2022-07-29 13:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/databaseH2/FilmDbService.java
> +            throw new NullPointerException("Incorrect id");
Создайте свое исключение. NullPointer кидается в других случаях. Хотя можете воспользоваться IllegalArgumentException

2022-07-29 13:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/databaseH2/FilmDbService.java
> +        jdbcTemplate.update(sqlQueryFilmsLike
У вас влазит все в 1 строку

2022-07-29 13:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/databaseH2/FilmDbService.java
> +        jdbcTemplate.update(sqlQueryFilmsCountLike
Тут все влазит в одну строку

2022-07-29 13:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/databaseH2/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate) {
пропустите строчку перед методом

2022-07-29 13:11 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmorate/service/databaseH2/UserDbService.java
> +package ru.yandex.practicum.filmorate.service.databaseH2;
я ба пакет переименовал. Можете сделать пакет db, а внутри h2. Просто использование заглавных букв в пакетах не привествуется

2022-07-30 05:39 UTC, amir-fatyhow commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public User(@NonNull String email, @NonNull String login, @NonNull LocalDate birthday,
Потому что при создании Usera не передается id

2022-07-30 05:42 UTC, amir-fatyhow commented on target/classes/application.properties
> +
12 строчка кода в gitignore

2022-07-30 06:37 UTC, amir-fatyhow commented on src/main/resources/data.sql
> +INSERT INTO genres(genre_id, genre)
"Включите в файл schema.sql создание таблиц. Если вам нужны некоторые данные в базе, их инициализация обычно описывается в файле data.sql — создайте его там же, где и schema.sql."

2022-07-30 06:51 UTC, closed without merging